### ISSUE TITLE
そらいろ start.mjo assemble error "unexpected token during switch case"

### ISSUE THREAD

**Issue by YuriSizuku** [trigger-segfault/majiro-py#4]
Thank you for your tool.  It works well on most of the scripts. 
  
But in some files the "unexpected token during switch case" occurs. Here's the log for this file

```shell
D:\Make\proc\github_galgame\majiro-py\src>python -m mjotool -G test -d start.mjo
group name: 'test'
Disassembling: start.mjo

D:\Make\proc\github_galgame\majiro-py\src>python -m mjotool -G test -a start.mjil
group name: 'test'
Assembling: start.mjil
Traceback (most recent call last):
  File "D:\Software\env\miniconda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Software\env\miniconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Make\proc\github_galgame\majiro-py\src\mjotool\__main__.py", line 479, in <module>
    exit(main())
  File "D:\Make\proc\github_galgame\majiro-py\src\mjotool\__main__.py", line 468, in main
    assembler.read()
  File "D:\Make\proc\github_galgame\majiro-py\src\mjotool\assembler.py", line 1392, in read
    self.parse_line()
  File "D:\Make\proc\github_galgame\majiro-py\src\mjotool\assembler.py", line 1052, in parse_line
    self.parse_instruction(token)
  File "D:\Make\proc\github_galgame\majiro-py\src\mjotool\assembler.py", line 1345, in parse_instruction
    raise Exception(f'unexpected token during switch case list operand parsing, got {token!r}')
Exception: unexpected token during switch case
```

The sample is here
[sorairo_start.mjo.zip](https://github.com/trigger-segfault/majiro-py/files/12330920/sorairo_start.mjo.zip)

**Comment by trigger-segfault** [comment]
Looks like switch cases weren't stopping at the end of the line, and it kept reading past that and saw the label and got confused. I pushed the fix to `master` (assuming you're using that branch and not `mj-lib-refactor`).

Please let me know if there are any other exceptions popping up, as I read @XHLin-gamer occasionally had to uncomment certain lines throwing exceptions to get things working.

**Comment by YuriSizuku** [comment]
Thank you very much.  It works now.
